name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.34.1

      - name: Build gh-pages
        run: |
          #curl -fsSL https://deno.land/x/install/install.sh | sh
          #export DENO_INSTALL="/home/runner/.deno"
          #export PATH="$DENO_INSTALL/bin:$PATH"
          export DENO_UNSAFE_HTTP=true
          deno --version
          deno install --unstable --allow-read --allow-write --allow-net --allow-run -n pagic https://deno.land/x/pagic@v1.6.3/mod.ts
          pagic build

      - name: Release "dist"
        uses: softprops/action-gh-release@v1
        with:
          body: 静态网页
          tag_name: github_run
          name: 1
          files: |
             ./dist/*
